
logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.coditas: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  schemes:
    - http
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true

application:
    toEmail: gawaias@rknec.edu

